"""
Pydantic data models for the Mindful Life AI application.
Defines the schema for daily check-ins, running logs, book entries,
journal entries, travel plans, and reviews.
"""

from datetime import date, datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


# ─── Enums ────────────────────────────────────────────────────────────

class RunType(str, Enum):
    EASY = "easy"
    TEMPO = "tempo"
    INTERVAL = "interval"
    LONG = "long"
    RECOVERY = "recovery"
    RACE = "race"
    CROSS_TRAIN = "cross_train"


class Genre(str, Enum):
    PHILOSOPHY = "philosophy"
    STOICISM = "stoicism"
    MINDFULNESS = "mindfulness"
    FICTION = "fiction"
    SCIENCE = "science"
    BIOGRAPHY = "biography"
    SELF_DEV = "self_development"
    HISTORY = "history"
    POETRY = "poetry"
    OTHER = "other"


class PromptTradition(str, Enum):
    THICH_NHAT_HANH = "thich_nhat_hanh"
    STOICISM = "stoicism"
    BLENDED = "blended"


class ReviewPeriod(str, Enum):
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"


class WorkCategory(str, Enum):
    SCHOOL = "school"
    DSA = "dsa"
    COURSES = "courses"
    JOB = "job"
    OTHERS = "others"
    # Monolith match
    PROJECTS = "projects"
    ADMIN = "admin"
    LEARNING = "learning"
    MEETINGS = "meetings"
    DAILY_LIFE = "daily_life"


# ─── Daily Check-In ──────────────────────────────────────────────────

class DailyCheckIn(BaseModel):
    """2-minute daily check-in capturing key metrics."""
    date: date
    sleep_time: Optional[str] = Field(None, description="Bedtime, e.g. '22:30'")
    wake_time: Optional[str] = Field(None, description="Wake time, e.g. '06:00'")
    sleep_hours: Optional[float] = Field(None, ge=0, le=24)
    steps: Optional[int] = Field(None, ge=0)
    meditation: bool = False
    meditation_minutes: Optional[int] = Field(None, ge=0)
    journal_words: Optional[int] = Field(None, ge=0)
    deep_work_hours: Optional[float] = Field(None, ge=0)
    energy: Optional[int] = Field(None, ge=1, le=10)
    alignment: Optional[int] = Field(None, ge=1, le=10)
    notes: Optional[str] = None
    # Morning planning
    morning_activities: Optional[list[dict]] = Field(None, description="List of {time, activity, completed}")
    intention: Optional[str] = Field(None, description="Morning intention for the day")

    # Exercises (e.g., walking, biking, strength training) in addition to running
    exercises: Optional[list[dict]] = Field(None, description="List of {type: str, duration_minutes: int}")


# ─── Work ────────────────────────────────────────────────────────────

class WorkSession(BaseModel):
    """Deep work session log."""
    date: date
    duration_minutes: int = Field(ge=0)
    category: WorkCategory = WorkCategory.OTHERS
    notes: Optional[str] = None


class WorkTask(BaseModel):
    """Tiimo-style daily activity planner task."""
    date: date
    name: str
    time_slot: Optional[str] = Field(None, description="e.g. '09:00-10:30'")
    category: WorkCategory = WorkCategory.OTHERS
    completed: bool = False
    duration_minutes: Optional[int] = Field(None, ge=0)
    order: Optional[int] = Field(0, description="Display order")


# ─── Running ─────────────────────────────────────────────────────────

class RunLog(BaseModel):
    """Post-run log entry with structured data extraction target."""
    date: date
    distance_km: float = Field(ge=0)
    duration_minutes: Optional[float] = Field(None, ge=0)
    run_type: RunType = RunType.EASY
    pace_per_km: Optional[str] = Field(None, description="e.g. '5:30'")
    heart_rate_avg: Optional[int] = None
    feel: Optional[str] = Field(None, description="How the run felt overall")
    pain_notes: Optional[str] = Field(None, description="Any pain or soreness")
    weather: Optional[str] = None
    mood_before: Optional[int] = Field(None, ge=1, le=10)
    mood_after: Optional[int] = Field(None, ge=1, le=10)
    notes: Optional[str] = Field(None, description="Free-form post-run notes or voice transcript")


class TrainingPlan(BaseModel):
    """Weekly training plan generated by the Running Coach agent."""
    week_start: date
    target_race: Optional[str] = None
    target_race_date: Optional[date] = None
    weeks_to_race: Optional[int] = None
    total_km: float
    days: list[dict] = Field(default_factory=list, description="List of daily plans")
    notes: str = ""


# ─── Reading ─────────────────────────────────────────────────────────

class BookEntry(BaseModel):
    """Book log entry with rating and reaction."""
    title: str
    author: str
    genre: Genre = Genre.OTHER
    date_started: Optional[date] = None
    date_finished: Optional[date] = None
    rating: Optional[int] = Field(None, ge=1, le=10)
    reaction: Optional[str] = Field(None, description="2-3 sentence reaction")
    pages: Optional[int] = None
    pages_read: Optional[int] = Field(0, ge=0, description="Current reading progress in pages")
    is_finished: bool = False
    status: str = "to read"  # to read, reading, read
    cover_url: Optional[str] = None


class ReadingProgressEntry(BaseModel):
    """Log pages read on a specific date."""
    book_id: str
    date: date
    pages_read: int = Field(ge=0)
    notes: Optional[str] = None


class BookNote(BaseModel):
    """A note or annotation for a specific book."""
    book_id: str
    date: date
    content: str
    pages_at_time: Optional[int] = Field(None, ge=0, description="Page number when note was written")


class ReadingStats(BaseModel):
    """Reading progress statistics."""
    total_books: int = 0
    books_this_year: int = 0
    yearly_goal: int = 50
    pace_percentage: float = 0.0
    on_track: bool = False
    genre_distribution: dict[str, int] = Field(default_factory=dict)
    underrepresented_genres: list[str] = Field(default_factory=list)


# ─── Journaling ──────────────────────────────────────────────────────

class JournalEntry(BaseModel):
    """Journal entry with optional prompt reference."""
    date: date
    content: str
    word_count: int = 0
    prompt_used: Optional[str] = None
    tradition: Optional[PromptTradition] = None
    mood: Optional[int] = Field(None, ge=1, le=10)
    tags: list[str] = Field(default_factory=list)
    themes: list[str] = Field(default_factory=list)


class JournalPrompt(BaseModel):
    """AI-generated journal prompt."""
    prompt: str
    tradition: PromptTradition
    context_reason: str = Field(description="Why this prompt was chosen given the user's current context")
    related_quote: Optional[str] = None
    quote_source: Optional[str] = None


# ─── Travel ──────────────────────────────────────────────────────────

class ExpenseCategory(str, Enum):
    FOOD = "food"
    TRANSPORT = "transport"
    ACCOMMODATION = "accommodation"
    ACTIVITIES = "activities"
    SHOPPING = "shopping"
    COFFEE = "coffee"
    OTHER = "other"


class TravelPlan(BaseModel):
    """Complete travel plan requiring user approval."""
    destination: str
    start_date: date
    end_date: date
    status: str = "draft"
    daily_itinerary: list[dict] = Field(default_factory=list)
    packing_list: list[str] = Field(default_factory=list)
    running_routes: list[dict] = Field(default_factory=list)
    budget_estimate: Optional[dict] = None
    currency: Optional[str] = None
    training_adjustments: Optional[str] = None
    journal_prompts: list[str] = Field(default_factory=list)


class TravelExpense(BaseModel):
    """Single travel expense entry."""
    date: date
    amount: float = Field(ge=0)
    currency: str = Field(default="VND", description="ISO currency code")
    category: ExpenseCategory = ExpenseCategory.OTHER
    description: Optional[str] = None
    trip: Optional[str] = Field(None, description="Trip name for grouping")
    amount_usd: Optional[float] = Field(None, description="Auto-converted USD amount")
    amount_vnd: Optional[float] = Field(None, description="Auto-converted VND amount")


# ─── Social ──────────────────────────────────────────────────────────

class SocialRelationship(str, Enum):
    FRIEND = "friend"
    ACQUAINTANCE = "acquaintance"
    PROFESSIONAL = "professional"
    COLLEAGUE = "colleague"
    FAMILY = "family"
    SOCIAL_EVENT = "social_event"
    TRAVEL_BUDDY = "travel_buddy"
    MENTOR = "mentor"


class SocialConnection(BaseModel):
    """Track a social interaction or meeting."""
    date: date
    name: str
    category: SocialRelationship = SocialRelationship.FRIEND
    context: Optional[str] = Field(None, description="Where/how you met or reconnected")
    location: Optional[str] = None
    notes: Optional[str] = None
    follow_up: Optional[str] = Field(None, description="Any follow-up planned")
    duration_minutes: Optional[int] = Field(None, ge=0, description="Duration of interaction in minutes")


# ─── Reviews ─────────────────────────────────────────────────────────

class WeeklyReview(BaseModel):
    """Auto-generated weekly review."""
    week_start: date
    week_end: date
    # Metrics
    total_km: float = 0
    meditation_days: int = 0
    meditation_pct: float = 0
    deep_work_hours: float = 0
    journal_word_count: int = 0
    books_finished: int = 0
    avg_energy: float = 0
    avg_alignment: float = 0
    # Five Non-Negotiables tracking
    sleep_consistency: float = 0
    meditation_consistency: float = 0
    steps_consistency: float = 0
    deep_work_consistency: float = 0
    therapy_checkin: bool = False
    # AI-generated
    narrative_summary: str = ""
    patterns_noticed: list[str] = Field(default_factory=list)
    integration_question: str = ""


class ReviewChecklist(BaseModel):
    """Structured review checklist for weekly/monthly/quarterly periods."""
    period: str = Field(description="weekly, monthly, or quarterly")
    start_date: date
    end_date: date
    categories: dict = Field(default_factory=dict, description="Dict of category -> list of checklist items")
    completed_items: list[str] = Field(default_factory=list, description="IDs of completed items")
    notes: Optional[str] = None


class ReviewRequest(BaseModel):
    """Request for generating a review."""
    period: ReviewPeriod
    start_date: Optional[date] = None
    end_date: Optional[date] = None


# ─── API Request/Response ────────────────────────────────────────────

class ChatMessage(BaseModel):
    """Generic chat message for free-form interaction with agents."""
    message: str
    agent: Optional[str] = Field(None, description="Target agent: running, reading, journaling, travel, review")
    context: Optional[dict] = None


class ChatResponse(BaseModel):
    """Response from the AI assistant."""
    response: str
    agent: str
    data: Optional[dict] = None
    suggestions: list[str] = Field(default_factory=list)
